name: ml_tddft
channels:
  - default
  - conda-forge
dependencies:
  - python==3.6.8
  - pymatgen==2019.7.2
  - pandas==0.25.0
  - scikit-learn==0.21.3
  - matplotlib==2.2.4
  - tensorflow==1.13.1
  - h5py==2.9.0
  - keras==2.2.4
  - spglib==1.9.10.1
  - jupyterlab<=1.13.1  # Last Py3.6 support
  - ase==3.22.0
  - pip
  - pip:
    - mdf_forge==0.7.3
    - matminer==0.4.3
    - parsl==1.1.0
    - cvxopt==1.2.2
    - -e .
