name: ml_tddft
channels:
  - default
  - matsci
  - conda-forge
dependencies:
  - python==3.6.8
  - pymatgen==2019.4.11
  - pandas==0.25.0
  - scikit-learn==0.21.3
  - matplotlib==2.2.4
  - tensorflow==1.13.1
  - h5py==2.9.0
  - keras==2.2.4
  - jupyterlab
  - pip
  - pip:
    - mdf_forge==0.7.3
    - matminer==0.4.3
    - ase==3.17.0
    - parsl==0.8.0
    - cvxopt==1.2.2
    - -e .
